
name: Build Android and iOS Binaries

on:
  push:
    branches:
      - main  # Trigger the workflow on pushes to the main branch

jobs:
  build-android:
    runs-on: ubuntu-latest  # Use Ubuntu for Android builds

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18  # Use Node.js 18 
        
      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin' # Use Temurin (Adoptium) JDK
          java-version: '17'      # Use Java 17 (or 11 if required)
      
      # Step 3: Install dependencies
      - name: Install dependencies
        run: npm install

      # Step 4: Build the SvelteKit app
      - name: Build SvelteKit app
        run: npm run build

      # Step 5: Install Capacitor
      - name: Install Capacitor
        run: npm install @capacitor/cli @capacitor/core

      # Step 6: Add Android platform
      - name: Add Android platform
        run: npx cap add android

      # Step 7: Build the Android app
      - name: Build Android app
        run: |
          cd android
          ./gradlew assembleDebug

      # Step 8: Upload APK as artifact
      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: app-debug.apk
          path: android/app/build/outputs/apk/debug/app-debug.apk